import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackButtonHandler from "@/components/BackButtonHandler";
import PullToRefresh from "@/components/PullToRefresh";
import NetworkStatus from "@/components/NetworkStatus";
import AnimatedLaunchScreen from "@/components/AnimatedLaunchScreen";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blink & Bliss CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AnimatedLaunchScreen>
          <BackButtonHandler />
          <NetworkStatus>
            <PullToRefresh>{children}</PullToRefresh>
          </NetworkStatus>
        </AnimatedLaunchScreen>
      </body>
    </html>
  );
}
